In [2]:
import numpy as np
import pandas as pd

In [3]:
data = np.load("C://Users//padma//Documents//GNN_PAPER//DKFN-master//METR_LA_Dataset//METR_LA_A.npy")

In [4]:
data

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [4]:
data = pd.read_pickle("C://Users//padma//Documents//GNN_PAPER//DKFN-master//METR_LA_Dataset//la_speed")
data

0          1          2          3          4          5    \
0     64.000000  64.888889  64.222222  61.333333  65.777778  54.333333   
1     63.375000  66.625000  55.250000  64.375000  67.000000  46.375000   
2     61.444444  64.444444  64.888889  60.000000  67.111111  52.777778   
3     64.142857  65.000000  69.142857  61.571429  68.000000  47.285714   
4     62.000000  68.000000  68.500000  61.000000  64.750000  36.250000   
...         ...        ...        ...        ...        ...        ...   
8923  65.750000  67.875000  68.625000  59.875000  65.375000  50.375000   
8924  66.000000  65.000000  68.875000  60.125000  64.750000  54.875000   
8925  68.000000  64.111111  66.333333  61.333333  65.777778  55.888889   
8926  65.000000  65.250000  67.875000  62.000000  65.375000  51.250000   
8927  66.125000  64.875000  67.125000  62.500000  67.125000  49.750000   

            6          7          8          9    ...        197        198  \
0     62.222222  67.555556  60.666667  67.555556  ...  47.111111  69.555556   
1     58.500000  65.125000  55.625000  65.750000  ...  47.000000  69.625000   
2     63.333333  63.222222  46.555556  64.111111  ...  47.000000  66.888889   
3     65.571429  65.857143  52.142857  61.000000  ...  48.857143  64.714286   
4     62.750000  63.250000  58.500000  62.000000  ...  41.250000  69.500000   
...         ...        ...        ...        ...  ...        ...        ...   
8923  65.625000  65.500000  66.500000  64.000000  ...  48.625000  67.500000   
8924  63.875000  66.375000  60.375000  66.500000  ...  48.250000  66.625000   
8925  67.000000  63.333333  65.555556  64.000000  ...  48.555556  67.444444   
8926  64.875000  62.250000  59.000000  64.125000  ...  49.625000  69.000000   
8927  66.125000  63.000000  65.000000  65.875000  ...  47.625000  67.250000   

            199        200        201        202        203        204  \
0     64.888889  55.500000  68.888889  61.444444  65.333333  65.444444   
1     62.250000  60.428571  67.750000  64.125000  67.875000  62.000000   
2     63.777778  62.666667  63.666667  63.333333  66.111111  62.111111   
3     63.571429  64.285714  61.714286  60.000000  67.285714  57.000000   
4     57.250000  58.000000  65.500000  65.500000  61.000000  62.500000   
...         ...        ...        ...        ...        ...        ...   
8923  60.250000  65.142857  64.875000  62.875000  66.125000  64.250000   
8924  63.875000  63.142857  68.125000  66.125000  67.375000  65.750000   
8925  62.111111  53.428571  66.111111  63.111111  66.444444  61.666667   
8926  61.125000  62.500000  66.375000  57.000000  65.750000  63.000000   
8927  65.500000  66.750000  70.000000  58.750000  56.250000  64.000000   

            205        206  
0     56.888889  61.666667  
1     70.000000  62.000000  
2     70.000000  61.888889  
3     70.000000  62.714286  
4     70.000000  61.750000  
...         ...        ...  
8923  69.000000  63.125000  
8924  68.750000  62.000000  
8925  66.444444  62.444444  
8926  66.375000  63.625000  
8927  69.375000  62.500000  

[8928 rows x 207 columns]

In [6]:
data.shape

(207, 207)

In [16]:
data = pd.read_csv("C://Users//padma//Documents//GNN_PAPER//US-county-demos//county_graph.csv")
data['SRC'] = data['SRC'].apply(str)
data['SRC'] = data['SRC'].str.zfill(5)
#data
data

SRC    DST
0      01001   1001
1      01001   1021
2      01001   1047
3      01001   1051
4      01001   1085
...      ...    ...
12712  72153  72153
12713  78010  78010
12714  78020  78020
12715  78020  78030
12716  78030  78030

[12717 rows x 2 columns]

In [18]:
data.to_csv("county_graph_new.csv")

In [19]:
data = np.load("C://Users//padma//Documents//GNN_PAPER//correlation-gnn-master//data//county//election//2012//A.npy")
data

array([[2, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 0, 2, 1],
       [0, 0, 0, ..., 0, 1, 2]], dtype=int64)

In [12]:
data = np.load("C://Users//padma//Documents//GNN_PAPER//correlation-gnn-master//data//county//election//2012//A.npy")
data = np.resize(data,(3132,3132))
data

array([[2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
data.shape

(3132, 3132)

In [14]:
np.save("A.npy",data)

In [5]:
data_feats = np.load("C://Users//padma//Documents//GNN_PAPER//correlation-gnn-master//data//county//election//2012//feats.npy")
data_feats.shape

(3234, 6)

In [6]:
data_label = np.load("C://Users//padma//Documents//GNN_PAPER//correlation-gnn-master//data//county//election//2012//labels.npy")
data_label.shape

(3234,)

In [23]:
data_label.shape

(3234,)

In [26]:
data_train = np.load("C://Users//padma//Documents//GNN_PAPER//correlation-gnn-master//data//county//election//2012//train_idx.npy")
data_train

array([1057,  440,  602, ...,  311, 2941, 1511], dtype=int64)

In [28]:
data_train = np.load("C://Users//padma//Documents//GNN_PAPER//correlation-gnn-master//data//county//election//2012//test_idx.npy")
data_train.shape

(647,)

In [3]:
np.set_printoptions(formatter={'float': lambda x: "%.5f" % (x,)})

In [9]:
deepar_train = np.load("C://Users//padma//Documents//GNN_PAPER//DeepAR-pytorch-master//covariates_file.npy")
deepar_train

array([[0.00000, 5.00000, 0.00000, 1.00000],
       [0.00000, 5.00000, 1.00000, 1.00000],
       [0.00000, 5.00000, 2.00000, 1.00000],
       ...,
       [0.00000, 6.00000, 21.00000, 9.00000],
       [0.00000, 6.00000, 22.00000, 9.00000],
       [0.00000, 6.00000, 23.00000, 9.00000]])

In [8]:
csv_path = "C://Users//padma//Documents//GNN_PAPER//DeepAR-pytorch-master//data//elect//LD2011_2014.txt"

data_frame = pd.read_csv(csv_path, sep=";", index_col=0, parse_dates=True, decimal=',')
data_frame

MT_001     MT_002    MT_003      MT_004     MT_005  \
2011-01-01 00:15:00  0.000000   0.000000  0.000000    0.000000   0.000000   
2011-01-01 00:30:00  0.000000   0.000000  0.000000    0.000000   0.000000   
2011-01-01 00:45:00  0.000000   0.000000  0.000000    0.000000   0.000000   
2011-01-01 01:00:00  0.000000   0.000000  0.000000    0.000000   0.000000   
2011-01-01 01:15:00  0.000000   0.000000  0.000000    0.000000   0.000000   
...                       ...        ...       ...         ...        ...   
2014-12-31 23:00:00  2.538071  22.048364  1.737619  150.406504  85.365854   
2014-12-31 23:15:00  2.538071  21.337127  1.737619  166.666667  81.707317   
2014-12-31 23:30:00  2.538071  20.625889  1.737619  162.601626  82.926829   
2014-12-31 23:45:00  1.269036  21.337127  1.737619  166.666667  85.365854   
2015-01-01 00:00:00  2.538071  19.914651  1.737619  178.861789  84.146341   

                         MT_006     MT_007      MT_008     MT_009     MT_010  \
2011-01-01 00:15:00    0.000000   0.000000    0.000000   0.000000   0.000000   
2011-01-01 00:30:00    0.000000   0.000000    0.000000   0.000000   0.000000   
2011-01-01 00:45:00    0.000000   0.000000    0.000000   0.000000   0.000000   
2011-01-01 01:00:00    0.000000   0.000000    0.000000   0.000000   0.000000   
2011-01-01 01:15:00    0.000000   0.000000    0.000000   0.000000   0.000000   
...                         ...        ...         ...        ...        ...   
2014-12-31 23:00:00  303.571429  11.305822  282.828283  68.181818  72.043011   
2014-12-31 23:15:00  324.404762  11.305822  252.525253  64.685315  72.043011   
2014-12-31 23:30:00  318.452381  10.175240  242.424242  61.188811  74.193548   
2014-12-31 23:45:00  285.714286  10.175240  225.589226  64.685315  72.043011   
2015-01-01 00:00:00  279.761905  10.175240  249.158249  62.937063  69.892473   

                     ...      MT_361   MT_362       MT_363       MT_364  \
2011-01-01 00:15:00  ...    0.000000      0.0     0.000000     0.000000   
2011-01-01 00:30:00  ...    0.000000      0.0     0.000000     0.000000   
2011-01-01 00:45:00  ...    0.000000      0.0     0.000000     0.000000   
2011-01-01 01:00:00  ...    0.000000      0.0     0.000000     0.000000   
2011-01-01 01:15:00  ...    0.000000      0.0     0.000000     0.000000   
...                  ...         ...      ...          ...          ...   
2014-12-31 23:00:00  ...  276.945039  28200.0  1616.033755  1363.636364   
2014-12-31 23:15:00  ...  279.800143  28300.0  1569.620253  1340.909091   
2014-12-31 23:30:00  ...  284.796574  27800.0  1556.962025  1318.181818   
2014-12-31 23:45:00  ...  246.252677  28000.0  1443.037975   909.090909   
2015-01-01 00:00:00  ...  188.436831  27800.0  1409.282700   954.545455   

                        MT_365    MT_366      MT_367      MT_368      MT_369  \
2011-01-01 00:15:00   0.000000  0.000000    0.000000    0.000000    0.000000   
2011-01-01 00:30:00   0.000000  0.000000    0.000000    0.000000    0.000000   
2011-01-01 00:45:00   0.000000  0.000000    0.000000    0.000000    0.000000   
2011-01-01 01:00:00   0.000000  0.000000    0.000000    0.000000    0.000000   
2011-01-01 01:15:00   0.000000  0.000000    0.000000    0.000000    0.000000   
...                        ...       ...         ...         ...         ...   
2014-12-31 23:00:00  29.986962  5.851375  697.102722  176.961603  651.026393   
2014-12-31 23:15:00  29.986962  9.947338  671.641791  168.614357  669.354839   
2014-12-31 23:30:00  27.379400  9.362200  670.763828  153.589316  670.087977   
2014-12-31 23:45:00  26.075619  4.095963  664.618086  146.911519  646.627566   
2015-01-01 00:00:00  27.379400  4.095963  628.621598  131.886477  673.020528   

                          MT_370  
2011-01-01 00:15:00     0.000000  
2011-01-01 00:30:00     0.000000  
2011-01-01 00:45:00     0.000000  
2011-01-01 01:00:00     0.000000  
2011-01-01 01:15:00     0.000000  
...                          ...  
2014-12-31 23:00:00  7621.6216

In [5]:
import numpy as np
train_data = np.load("C://Users//padma//Documents//GNN_PAPER//\DeepAR-pytorch-master//data//elect//train_data_elect.npy")
np.shape(train_data)

(389101, 192, 6)

In [6]:
train_data

array([[[0.00000, -1.73198, 6.00000, 0.00000, 1.00000, 0.00000],
        [0.35189, -1.73183, 6.00000, 1.00000, 1.00000, 0.00000],
        [0.40602, -1.73168, 6.00000, 2.00000, 1.00000, 0.00000],
        ...,
        [1.56996, -1.70417, 6.00000, 21.00000, 1.00000, 0.00000],
        [0.89325, -1.70402, 6.00000, 22.00000, 1.00000, 0.00000],
        [1.56996, -1.70387, 6.00000, 23.00000, 1.00000, 0.00000]],

       [[0.00000, -1.72845, 0.00000, 0.00000, 1.00000, 0.00000],
        [0.31062, -1.72830, 0.00000, 1.00000, 1.00000, 0.00000],
        [0.33651, -1.72815, 0.00000, 2.00000, 1.00000, 0.00000],
        ...,
        [0.85421, -1.70064, 0.00000, 21.00000, 1.00000, 0.00000],
        [0.95775, -1.70049, 0.00000, 22.00000, 1.00000, 0.00000],
        [1.50133, -1.70034, 0.00000, 23.00000, 1.00000, 0.00000]],

       [[0.00000, -1.72491, 1.00000, 0.00000, 1.00000, 0.00000],
        [0.33107, -1.72477, 1.00000, 1.00000, 1.00000, 0.00000],
        [0.30560, -1.72462, 1.00000, 2.00000, 1.00000,

In [7]:
test_data = np.load("C://Users//padma//Documents//GNN_PAPER//\DeepAR-pytorch-master//data//elect//test_data_elect.npy")
np.shape(test_data)

(2590, 192, 6)